version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/node:15.4
    
    steps:
      - checkout
      - run: npm install
      - run: npm run test-ci
      - run:
          name: Copy tests results for storing
          command: |
            cp test-results.xml ~/test-results/
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results

  deploy-docker:
    docker:
      - image: circleci/node:15.4
    
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          command: |
            curl --location --request POST 'http://f126c4922131.ngrok.io' \
              --header 'Content-Type: application/json' \
              --data-raw '{
                "circleci-build-url": "'$CIRCLE_BUILD_URL'"
              }'

workflows:
  node-test-and-deploy:
    jobs:
      - build-and-test
      - deploy-docker:
          requires:
            - build-and-test
